# Generated by Django 3.1.6 on 2021-02-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_city_unity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='القطاع')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locality', verbose_name='المحلية')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state', verbose_name='الولاية')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='المكتب')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locality', verbose_name='المحلية')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state', verbose_name='الولاية')),
                ('unity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.unity', verbose_name='الوحدة الادارية')),
            ],
        ),
        migrations.CreateModel(
            name='Hquarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الامانة')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state', verbose_name='الولاية')),
            ],
        ),
    ]
